- .appveyor.yml
- .gitignore
- .travis.yml
- JUCE.cmake
- README.md
- cmake/AppConfig.h
- cmake/CMakejucer.cmake
- cmake/JuceHeader.h
- cmake/ModuleWrapper.cpp
- examples/HelloWorld/CMakeLists.txt
@MartyLake: please have a look at this first PR, and tell me if anything looks weird, thanks!
> Build JUCE's HelloWorld example using CMake

- .appveyor.yml
- .travis.yml
Supersedes https://github.com/McMartin/JUCE.cmake/pull/3 and finally fixes the warnings on Travis CI.
@MartyLake: please have a look, thanks!
> Indicate build configuration to CMake

- .appveyor.yml
- .travis.yml
- cmake/CMakejucer.cmake
- examples/CMakeLists.txt
- examples/OSCMonitor/CMakeLists.txt
Fixes the issue encountered in #2.
> Support more JUCE modules

- extras/AudioPerformanceTest/CMakeLists.txt
- extras/CMakeLists.txt
> Support building AudioPerformanceTest tool

- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/CMakejucer.cmake
- examples/AnimationAppExample/CMakeLists.txt
- examples/AudioAppExample/CMakeLists.txt
- examples/BouncingBallWavetableDemo/CMakeLists.txt
- examples/ComponentTutorialExample/CMakeLists.txt
- examples/HelloWorld/CMakeLists.txt
- examples/MPETest/CMakeLists.txt
- examples/MidiTest/CMakeLists.txt
- examples/NetworkGraphicsDemo/CMakeLists.txt
- examples/OSCMonitor/CMakeLists.txt
- examples/OSCReceiver/CMakeLists.txt
- examples/OSCSender/CMakeLists.txt
- examples/OpenGLAppExample/CMakeLists.txt
- examples/PluckedStringsDemo/CMakeLists.txt
- examples/SimpleFFTExample/CMakeLists.txt
- examples/audio plugin host/CMakeLists.txt
- extras/AudioPerformanceTest/CMakeLists.txt
- extras/CMakeLists.txt
- extras/UnitTestRunner/CMakeLists.txt
- extras/binarybuilder/CMakeLists.txt
This PR addresses the TODO that was introduced in #10 (https://github.com/McMartin/JUCE.cmake/commit/f5a072749f2b56e5514e2f59785e0ed31024acdb#diff-f6a677b37496c3a44ddfd0d328ce917eR99).
This first commit message starts with `[!API]` to indicate that it breaks the API, i.e. clients have to change their code (obviously that commit adapts the clients that live in the repo).
> Support building consoleapp projects

- .travis.yml
> Use Xcode on Mac like the Projucer does

- .travis.yml
- cmake/CMakejucer.cmake
- cmake/Info-App-Xcode.plist
> Mimic the Projucer better

- cmake/CMakejucer.cmake
- cmake/resources.rc
> Generate resources.rc file like Projucer

- cmake/Reprojucer.cmake
- examples/audio plugin host/CMakeLists.txt
> Add VST3 include directory from Reprojucer

- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/Reprojucer.cmake
- examples/AnimationAppExample/CMakeLists.txt
- examples/AudioAppExample/CMakeLists.txt
- examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- examples/BLOCKS/BlocksSynth/CMakeLists.txt
- examples/BouncingBallWavetableDemo/CMakeLists.txt
- examples/ComponentTutorialExample/CMakeLists.txt
- examples/Demo/CMakeLists.txt
- examples/HelloWorld/CMakeLists.txt
- examples/MPETest/CMakeLists.txt
- examples/MidiTest/CMakeLists.txt
- examples/NetworkGraphicsDemo/CMakeLists.txt
- examples/OSCMonitor/CMakeLists.txt
- examples/OSCReceiver/CMakeLists.txt
- examples/OSCSender/CMakeLists.txt
- examples/OpenGLAppExample/CMakeLists.txt
- examples/PluckedStringsDemo/CMakeLists.txt
- examples/SimpleFFTExample/CMakeLists.txt
- examples/audio plugin host/CMakeLists.txt
- extras/AudioPerformanceTest/CMakeLists.txt
- extras/Projucer/CMakeLists.txt
- extras/UnitTestRunner/CMakeLists.txt
- extras/binarybuilder/CMakeLists.txt
> Pass project name like other settings

- cmake/Reprojucer.cmake
#23 introduced a broken feature, so let's fix it!
@MartyLake: please review, thanks! (nothing to test on Mac though)
> Fix generating resources.rc file

- cmake/Reprojucer.cmake
> Support building BinaryDataBuilding with different generators

- .appveyor.yml
- .travis.yml
> Adapt to JUCE depending on VST3 SDK 3.6.7

- README.md
> Make GitHub display the AppVeyor and Travis CI badges properly

- cmake/BinaryDataBuilder/CMakeLists.txt
- examples/AnimationAppExample/CMakeLists.txt
- examples/AudioAppExample/CMakeLists.txt
- examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- examples/BLOCKS/BlocksSynth/CMakeLists.txt
- examples/BouncingBallWavetableDemo/CMakeLists.txt
- examples/ComponentTutorialExample/CMakeLists.txt
- examples/Demo/CMakeLists.txt
- examples/HelloWorld/CMakeLists.txt
- examples/MPETest/CMakeLists.txt
- examples/MidiTest/CMakeLists.txt
- examples/NetworkGraphicsDemo/CMakeLists.txt
- examples/OSCMonitor/CMakeLists.txt
- examples/OSCReceiver/CMakeLists.txt
- examples/OSCSender/CMakeLists.txt
- examples/OpenGLAppExample/CMakeLists.txt
- examples/PluckedStringsDemo/CMakeLists.txt
- examples/SimpleFFTExample/CMakeLists.txt
- examples/audio plugin demo/CMakeLists.txt
- examples/audio plugin host/CMakeLists.txt
- extras/AudioPerformanceTest/CMakeLists.txt
- extras/Projucer/CMakeLists.txt
- extras/UnitTestRunner/CMakeLists.txt
- extras/binarybuilder/CMakeLists.txt
> Add file check existence and improve computing paths

- cmake/Reprojucer.cmake
> Mark incidental information as such

- .appveyor.yml
- .travis.yml
> Clone JUCE repository from its new location

- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/Reprojucer.cmake
@MartyLake: please review, thanks! Don't hesitate to tell me if some commit messages are not clear enough, I can extend/reword them.
> Make BinaryDataBuilder configurable without JUCE_ROOT being defined

- .appveyor.yml
- .travis.yml
JUCE.cmake doesn't support JUCE 5 yet.
> Reset JUCE to the last commit of version 4.3.1

- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/Reprojucer.cmake
> Require CMake version 3.4

- .travis.yml
> Make Travis CI try again to download the VST3 SDK when it fails

- .appveyor.yml
- .travis.yml
- Jucer2CMake/CMakeLists.txt
- Jucer2CMake/main.cpp
> Remove the dependency on Projucer

- README.md
> Add repo description, Requirements, Getting started and License sections to README

- Jucer2CMake/CMakeLists.txt
- Jucer2CMake/main.cpp
> Handle preprocessor definitions written one per line

- cmake/Reprojucer.cmake
> Compile Objective-C++ sources on OSX only

- Jucer2CMake/main.cpp
> Fix joining pre-processor definitions

- .appveyor.yml
> Build also with Visual Studio 2013 on AppVeyor

- Jucer2CMake/main.cpp
> Avoid assertion when creating a juce::File with a relative path

- cmake/Reprojucer.cmake
> Remove unneeded indirection

- cmake/Reprojucer.cmake
> Fix jucer_export_target_configuration() function

- Jucer2CMake/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2CMake/main.cpp
- cmake/Reprojucer.cmake
Resolves https://github.com/McMartin/JUCE.cmake/issues/77.
> Support "VST3 SDK Folder" export target setting properly

- cmake/Reprojucer.cmake
> Fix enabling C++11

- Jucer2CMake/main.cpp
Alternative to #116.
@MartyLake: please review this PR and #116 and tell me which one you prefer, thanks!
> Fix handling "Header search paths" configuration setting in Jucer2CMake

- Jucer2CMake/generated/JUCE/examples/AUv3Synth/CMakeLists.txt
- Jucer2CMake/main.cpp
- cmake/Reprojucer.cmake
Resolves https://github.com/McMartin/JUCE.cmake/issues/119.
> Support Xcode Resource files

- cmake/Reprojucer.cmake
@MartyLake: please test with the Make generator and review, thanks!
> Fix setting CMAKE_OSX_SYSROOT when using the Make generator

- .appveyor.yml
- .travis.yml
- Jucer2CMake/generated/apply-Jucer2CMake-to-JUCE-jucers.cmake
- Jucer2CMake/main.cpp
> Check generated CMakeLists.txt files are up to date

- Jucer2CMake/main.cpp
> Fix building Jucer2CMake with JUCE 4.2.0

- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BouncingBallWavetableDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/Demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/HelloWorld/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MPETest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MidiTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/NetworkGraphicsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCReceiver/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCSender/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PluckedStringsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/SimpleFFTExample/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/AudioPerformanceTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/Projucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/UnitTestRunner/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support "Warning Level" configuration setting

- .travis.yml
- Jucer2Reprojucer/CMakeLists.txt
- ci/CMakeLists.txt
- cmake/Reprojucer.cmake
> Build Projucer on Linux

- .travis.yml
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- ci/CMakeLists.txt
- cmake/Reprojucer.cmake
Resolves #77 (especially that comment: https://github.com/McMartin/JUCE.cmake/issues/77#issuecomment-305494288) 
> Support VST3 only on macOS and Windows

- .travis.yml
- ci/CMakeLists.txt
- cmake/Reprojucer.cmake
>  Build JuceDemoPlugin on Linux

- Jucer2Reprojucer/main.cpp
> Translate user notes into comments

- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BouncingBallWavetableDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/Demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/HelloWorld/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MPETest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MidiTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/NetworkGraphicsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCReceiver/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCSender/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PluckedStringsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/SimpleFFTExample/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/AudioPerformanceTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/Projucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/UnitTestRunner/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support "Treat warnings as errors" configuration setting

- cmake/Reprojucer.cmake
This should have been done in #169.
> Support VST3 only on macOS and Windows for real

- Jucer2Reprojucer/main.cpp
> Various improvements

- .appveyor.yml
- .travis.yml
- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Do not provide default values for VST3_SDK_FOLDER

- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/commits.hpp
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support the "VST SDK Folder" setting

- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BouncingBallWavetableDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/Demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/HelloWorld/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MPETest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MidiTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/NetworkGraphicsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCReceiver/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCSender/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PluckedStringsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/SimpleFFTExample/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/AudioPerformanceTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/Projucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/UnitTestRunner/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support the "Platform Toolset" exporter setting

- cmake/Reprojucer.cmake
> Fix setting CMAKE_BUILD_TYPE

- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BouncingBallWavetableDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/Demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/HelloWorld/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MPETest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MidiTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/NetworkGraphicsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCReceiver/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCSender/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/AudioPerformanceTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/Projucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/UnitTestRunner/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/binarybuilder/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
>  Support the "Architecture" setting of the Linux Makefile exporter

- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BouncingBallWavetableDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/Demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/HelloWorld/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MPETest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MidiTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/NetworkGraphicsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCReceiver/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCSender/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/AudioPerformanceTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/Projucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/UnitTestRunner/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/binarybuilder/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support the "pkg-config libraries" setting

- cmake/Reprojucer.cmake
> Support the "Architecture" setting of the Visual Studio exporters

- cmake/Reprojucer.cmake
Fixes https://github.com/McMartin/JUCE.cmake/issues/193.
@MartyLake, @WGuLL: please review, thanks!
> Only add Xcode resources to sources on macOS

- README.md
We don't say "the CMake", "the Visual Studio" or "the Xcode".
> Talk about Projucer like any other piece of software

- Jucer2Reprojucer/CMakeLists.txt
- README.md
- ci/CMakeLists.txt
- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/IconBuilder/CMakeLists.txt
- cmake/Reprojucer.cmake
This PR fixes a bug and makes some ground work for upcoming feature PRs on `Reprojucer.cmake`.
> Be stricter about export targets and build configurations

- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BouncingBallWavetableDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/Demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/HelloWorld/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MPETest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MidiTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/NetworkGraphicsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCReceiver/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCSender/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PluckedStringsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/SimpleFFTExample/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/AudioPerformanceTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/Projucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/UnitTestRunner/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support the "Runtime Library" build configuration setting

- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BouncingBallWavetableDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/Demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/HelloWorld/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MPETest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MidiTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/NetworkGraphicsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCReceiver/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCSender/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PluckedStringsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/SimpleFFTExample/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/AudioPerformanceTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/Projucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/UnitTestRunner/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support the "Whole Program Optimisation" build configuration setting

- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/BouncingBallWavetableDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/Demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/HelloWorld/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MPETest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/MidiTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/NetworkGraphicsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCReceiver/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/OSCSender/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PluckedStringsDemo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/SimpleFFTExample/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/AudioPerformanceTest/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/Projucer/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE/extras/UnitTestRunner/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support the "Character Set" build configuration setting

- Jucer2Reprojucer/main.cpp
> Translate non-default maxBinaryFileSize project setting to CMake

- .appveyor.yml
- .travis.yml
- ci/CMakeLists.txt
- ci/JuceProjects/CMakeLists.txt
- ci/ReprojucerHelpers/CMakeLists.txt
> Improve CI

- .appveyor.yml
- .travis.yml
- Jucer2Reprojucer/generated/JUCE/CMakeLists.txt
> Improve CI again

- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/AUv3Synth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/audio plugin host/CMakeLists.txt
- Jucer2Reprojucer/generated/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
- Jucer2Reprojucer/main.cpp
> More small fixes for JUCE 4.2.0

- cmake/Reprojucer.cmake
> Fix setting target properties that depend on $<CONFIG>

- cmake/Reprojucer.cmake
> Fix setting CMAKE_OSX_SYSROOT and CMAKE_OSX_DEPLOYMENT_TARGET

- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/BinaryDataBuilder/Source/jucer_Headers.h
- cmake/IconBuilder/CMakeLists.txt
- cmake/IconBuilder/Source/Project Saving/jucer_ProjectExporter.h
- cmake/IconBuilder/Source/jucer_Headers.h
- cmake/IconBuilder/main.cpp
> Do not use Reprojucer.cmake to configure its helper executables

- cmake/BinaryDataBuilder/main.cpp
- cmake/IconBuilder/CMakeLists.txt
- cmake/IconBuilder/main.cpp
- cmake/PListMerger/CMakeLists.txt
- cmake/PListMerger/main.cpp
- cmake/Reprojucer.cmake
> Some fixes and small improvements

- cmake/BinaryDataBuilder/Source/Project/jucer_Project.h
- cmake/BinaryDataBuilder/main.cpp
- cmake/Reprojucer.cmake
- cmake/templates/AppConfig.h
- cmake/templates/JuceHeader.h
Currently based on top of https://github.com/McMartin/JUCE.cmake/pull/233
> Generate BinaryData.h exactly like Projucer does

- .gitignore
- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/IconBuilder/CMakeLists.txt
- cmake/PListMerger/CMakeLists.txt
- cmake/Reprojucer.cmake
Currently based on top of #234, which is based on top of #233.
> Share helper executables between projects

- README.md
> Replace broken hyperlink in README.md

- .appveyor.yml
- .travis.yml
- ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
> Move script used only on CI to ci/ folder

- cmake/Reprojucer.cmake
> Support the "Dynamic Library" project type

- cmake/IconBuilder/main.cpp
> Fix memory leak assertion when IconBuilder exits

- README.md
An upcoming PR will add a bunch of Markdown files, so let's get the style right for the main Markdown file of the repo, README.md.
> Make some minor style improvements on README.md

- cmake/Reprojucer.cmake
- tests/issue-246/CMakeLists.txt
- tests/issue-246/main.cpp
Resolves #246 
@MartyLake, @Xav83: please review, thanks!
> Fix bug reported in issue #246

- cmake/Reprojucer.cmake
> Use string() instead of list()

- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/AUv3Synth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/AUv3Synth/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Acknowledge missing features

- cmake/Reprojucer.cmake
> Catch target name mistakes

- cmake/Reprojucer.cmake
- doc/Reprojucer.cmake/README.rst
- doc/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
- doc/Reprojucer.cmake/command/jucer_export_target.rst
- doc/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- doc/Reprojucer.cmake/command/jucer_project_begin.rst
- doc/Reprojucer.cmake/command/jucer_project_end.rst
- doc/Reprojucer.cmake/command/jucer_project_files.rst
- doc/Reprojucer.cmake/command/jucer_project_module.rst
- doc/Reprojucer.cmake/command/jucer_project_settings.rst
> Add some documentation about Reprojucer.cmake

- .appveyor.yml
- .travis.yml
- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/BinaryDataBuilder/main.cpp
> Build Reprojucer.cmake and Jucer2Reprojucer helpers with JUCE 5.0.0

- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/BLOCKS/BlocksDrawing/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/BLOCKS/BlocksMonitor/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/BLOCKS/BlocksSynth/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- cmake/templates/AppConfig.h
- doc/Reprojucer.cmake/README.rst
- doc/Reprojucer.cmake/command/jucer_appconfig_header.rst
> Read and write the user code section in AppConfig.h

- cmake/Reprojucer.cmake
>  Fix writing audio plugin settings defines in AppConfig.h

- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/AUv3Synth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.2.0/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/AUv3Synth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/PlugInSamples/Arpeggiator/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/PlugInSamples/GainPlugIn/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/PlugInSamples/MultiOutSynth/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/PlugInSamples/NoiseGate/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/PlugInSamples/Surround/CMakeLists.txt
- Jucer2Reprojucer/generated/JUCE-4.3.1/examples/audio plugin demo/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- doc/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
This PR is currently based on top of #265 
> Acknowledge missing support for RTAS and AAX plugin formats

- .travis.yml
> Use cmake3 package instead of downloading CMake manually

- .appveyor.yml
- ci/AllJuceProjects/CMakeLists.txt
- ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
- cmake/Reprojucer.cmake
> Miscellaneous improvements

- cmake/Reprojucer.cmake
>  Do not warn on platforms that cannot build certain plugins

- README.md
- doc/Reprojucer.cmake/README.rst
> Fix exporter name in documentation

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- doc/Reprojucer.cmake/command/jucer_project_settings.rst
> Improve JUCE 5.0.0 support

- cmake/Reprojucer.cmake
> Replace wrong usage of LESS by VERSION_LESS

- .travis.yml
> Make FRUT pass CI on xcode8.3 images of Travis CI

- cmake/Reprojucer.cmake
> Simplify appending to a target property

- cmake/Reprojucer.cmake
> Simplify the condition to set JucePlugin_Build_* defines

- cmake/Reprojucer.cmake
> Don't restrict the "Company Copyright" project setting to JUCE 5.2.0

- cmake/Reprojucer.cmake
> Add missing options on Windows

- Jucer2Reprojucer/main.cpp
- generated/JUCE-5.2.0/examples/DSP module plugin demo/CMakeLists.txt
> Fix two bugs in Jucer2Reprojucer

- Jucer2Reprojucer/main.cpp
A pure C++ PR with a net line diff of -145!
> Improve conversions in Jucer2Reprojucer

- Jucer2Reprojucer/main.cpp
A small mistake appeared during one of the many git rebase done on
improve-conversions-in-Jucer2Reprojucer (https://github.com/McMartin/FRUT/pull/304).
> Fix small rebase mistake

- cmake/Reprojucer.cmake
> Append to string more carefully

- cmake/Reprojucer.cmake
> Put all private functions in a FRUT "namespace"

- cmake/Reprojucer.cmake
Fixes #312
@lethal-guitar, @MartyLake: please review, thanks !
> Fix calling set_source_files_properties()

- cmake/Reprojucer.cmake
This PR is basically b29e3c1ad470989035b4cffe7773947f3231ce1d and 0cee374d2fb2ed79baa3ed6df3cdc7487b5f7e86 extracted out of #310.
> Use more but smaller loops

- cmake/Reprojucer.cmake
> Make Reprojucer.cmake testable

- .appveyor.yml
- .gitignore
- .travis.yml
- CMakeLists.txt
- Jucer2Reprojucer/CMakeLists.txt
- ci/AllJuceProjects/CMakeLists.txt
- ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/IconBuilder/CMakeLists.txt
- cmake/PListMerger/CMakeLists.txt
> Make FRUT installable

- cmake/Reprojucer.cmake
> Fix missing icons

- Jucer2Reprojucer/main.cpp
> Make Jucer2Reprojucer check second argument

- Jucer2Reprojucer/main.cpp
> Prefer juce::String and juce::StringArray to std::string and std::vector<std::string>

- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
> Use "keyword" instead of "tag"

- Jucer2Reprojucer/main.cpp
> Put CXX_LANGUAGE_STANDARD after BINARYDATA_NAMESPACE like Projucer does

- .travis.yml
- Jucer2Reprojucer/CMakeLists.txt
Fixes #336.
@MartyLake, @Xav83: please review, thanks!
> Build with the latest Xcode version on Travis CI

- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
- docs/Reprojucer.cmake/command/jucer_export_target.rst
> Don't document unsupported features

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support the "USE_HEADERMAP" Xcode exporter setting

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- generated/JUCE-5.2.0/examples/AnalyticsCollection/CMakeLists.txt
- generated/JUCE-5.2.0/examples/PushNotificationsDemo/CMakeLists.txt
- generated/JUCE-5.2.0/extras/Projucer/CMakeLists.txt
> Support the "VST/VST3 Binary Location" VS configuration properties

- .github/pull_request_template.md
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
> Stop forgetting about the docs

- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
Resolves #267 🎉 
@Xav83: please try this out, thanks!
> Support building AAX plugins

- ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
- cmake/Reprojucer.cmake
> Add and remove some message(FATAL_ERROR)

- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
> Support building RTAS plugins

- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
- docs/Reprojucer.cmake/command/jucer_project_files.rst
- docs/Reprojucer.cmake/command/jucer_project_module.rst
- docs/Reprojucer.cmake/command/jucer_project_settings.rst
> Improve docs

- Jucer2Reprojucer/CMakeLists.txt
- cmake/Reprojucer.cmake
@MartyLake, @scotchi: please review, thanks!
> Support JUCE projects that don't have a .jucer file

- Jucer2Reprojucer/main.cpp
> Don't construct a new locale for every call to std::isalpha

- cmake/Reprojucer.cmake
> Improve globbing source files from JUCE modules

- cmake/Reprojucer.cmake
> Check SDK folders and emit warnings only once

- .travis.yml
> Use xcode9.4 image on Travis CI

- cmake/Reprojucer.cmake
> Improve usage of if() command

- .travis.yml
> Build FRUT with an older version of Xcode

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
> Support the "Plugin Formats" and "Plugin Characteristics" project settings

- cmake/Reprojucer.cmake
> Use a cleaner way of bundling the PkgInfo file

- Jucer2Reprojucer/main.cpp
> Deal with certain audio plugin settings being undefined

- Jucer2Reprojucer/main.cpp
> Parse preprocessor definitions like Projucer does

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Support newest macOS SDKs

- cmake/Reprojucer.cmake
- cmake/templates/AUv3.entitlements
> Support adding entitlements to AUv3 plugins

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- generated/JUCE-5.2.1/examples/PushNotificationsDemo/CMakeLists.txt
> Handle gracefully settings that are know but not supported

- Jucer2Reprojucer/main.cpp
- README.rst
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- docs/Reprojucer.cmake/index.rst
- docs/index.rst
Resolves #228.
@Pwera, @MrPointer: FYI
> Support the "Code::Blocks (Windows)" export target

- .appveyor.yml
- .travis.yml
> Speed-up CI by re-using the same binary directory

- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/BinaryDataBuilder/Source/jucer_Headers.h
> Cleanup: Remove unneeded dependency on juce_cryptography

- .clang-format
- Jucer2Reprojucer/main.cpp
- cmake/BinaryDataBuilder/Source/Project/jucer_Project.h
- cmake/BinaryDataBuilder/main.cpp
> Reformat C++ code using the latest clang-format

- .appveyor.yml
- .travis.yml
> Build FRUT with MinGW on CI

- .travis.yml
- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- README.rst
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- docs/Reprojucer.cmake/index.rst
> Support the "Code::Blocks (Linux)" export target

- tests/test-projects/no-modules/consoleapp521/Builds/MacOSX/consoleapp521.xcodeproj/project.pbxproj
- tests/test-projects/no-modules/consoleapp521/Builds/VisualStudio2013/consoleapp521.sln
- tests/test-projects/no-modules/consoleapp521/Builds/VisualStudio2013/consoleapp521_ConsoleApp.vcxproj
- tests/test-projects/no-modules/consoleapp521/Builds/VisualStudio2015/consoleapp521.sln
- tests/test-projects/no-modules/consoleapp521/Builds/VisualStudio2015/consoleapp521_ConsoleApp.vcxproj
- tests/test-projects/no-modules/consoleapp521/Builds/VisualStudio2017/consoleapp521.sln
- tests/test-projects/no-modules/consoleapp521/Builds/VisualStudio2017/consoleapp521_ConsoleApp.vcxproj
- tests/test-projects/no-modules/consoleapp521/consoleapp521.jucer
- tests/test-projects/no-modules/consoleapp531/Builds/MacOSX/consoleapp531.xcodeproj/project.pbxproj
- tests/test-projects/no-modules/consoleapp531/Builds/VisualStudio2013/consoleapp531.sln
- tests/test-projects/no-modules/consoleapp531/Builds/VisualStudio2013/consoleapp531_ConsoleApp.vcxproj
- tests/test-projects/no-modules/consoleapp531/Builds/VisualStudio2015/consoleapp531.sln
- tests/test-projects/no-modules/consoleapp531/Builds/VisualStudio2015/consoleapp531_ConsoleApp.vcxproj
- tests/test-projects/no-modules/consoleapp531/Builds/VisualStudio2017/consoleapp531.sln
- tests/test-projects/no-modules/consoleapp531/Builds/VisualStudio2017/consoleapp531_ConsoleApp.vcxproj
- tests/test-projects/no-modules/consoleapp531/consoleapp531.jucer
> Add missing project IDs

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
> Support the "Force Generation of Debug Symbols" configuration setting

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- generated/JUCE-5.2.1/examples/AnalyticsCollection/CMakeLists.txt
- generated/JUCE-5.2.1/examples/Demo/CMakeLists.txt
- generated/JUCE-5.2.1/examples/PushNotificationsDemo/CMakeLists.txt
- generated/JUCE-5.2.1/examples/audio plugin host/CMakeLists.txt
- generated/JUCE-5.2.1/extras/Projucer/CMakeLists.txt
- generated/JUCE-5.2.1/extras/UnitTestRunner/CMakeLists.txt
- generated/JUCE-5.3.1/extras/AudioPluginHost/CMakeLists.txt
- generated/JUCE-5.3.1/extras/Projucer/CMakeLists.txt
- generated/JUCE-5.3.1/extras/UnitTestRunner/CMakeLists.txt
> Support the "Debug Information Format" configuration setting

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
> Support the "Windows Target Platform" exporter setting

- CODE_OF_CONDUCT.md
- README.rst
We use the Contributor Covenant Code of Conduct.
@MartyLake: FYI
> Add CODE_OF_CONDUCT.md

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- generated/JUCE-5.2.1/extras/Projucer/CMakeLists.txt
- generated/JUCE-5.3.1/extras/Projucer/CMakeLists.txt
> Support the "Link-Time Optimisation" setting on all configurations

- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- Jucer2Reprojucer/third-party/argh/LICENSE
- Jucer2Reprojucer/third-party/argh/argh.h
Big thanks to @adishavit for https://github.com/adishavit/argh! 👏
> Support converting modules that use global paths

- .travis.yml
- generated/JUCE-4.2.0/CMakeLists.txt
- generated/JUCE-4.3.1/CMakeLists.txt
- generated/JUCE-5.0.0/CMakeLists.txt
- generated/JUCE-5.2.1/CMakeLists.txt
- generated/JUCE-5.3.1/CMakeLists.txt
This should have been done in #418.
> Build FRUT with the "Code::Blocks Linux" exporter on CI for real

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
> Support the "Plugin AU is sandbox safe" audio plugin project setting

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
> Support the "Microphone Access" and "Camera Access" exporter settings

- .appveyor.yml
- .azure-pipelines.yml
- README.rst
- ci/azure-pipelines-steps.yml
> Replace AppVeyor by Azure Pipelines for CI using Visual Studio

- Jucer2Reprojucer/main.cpp
- README.rst
- ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
> Don't require defining any variable by default

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
> Handle unsupported but known settings

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
> Treat VST plugin format as legacy like Projucer does

- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- README.rst
- cmake/Reprojucer.cmake
> Support disabling warnings in JUCE modules

- README.rst
@gonzaloflirt, @WGuLL, @Xav83, @lethal-guitar, @PioBeat, @dscheffer, @scotchi, @IqraShahzad1, @rclement: thank you all for contributing to FRUT!
> Acknowledge and thank all contributors of FRUT

- cmake/Reprojucer.cmake
> Improve and refactor dealing with macOS SDKs

- .appveyor.yml
- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
> Do not write CR+LF line endings by default

- cmake/Reprojucer.cmake
> Do not assume MSVC means Visual Studio

- README.rst
- docs/Reprojucer.cmake/index.rst
- docs/index.rst
> Improve hyperlinks in README and docs

- FRUT.svg
- README.rst
> Add new sections and logo to README 

- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- generated/JUCE-5.3.1/examples/DemoRunner/CMakeLists.txt
- generated/JUCE-5.4.3/examples/DemoRunner/CMakeLists.txt
- tests/test-projects/no-modules/consoleapp521/CMakeLists.txt
- tests/test-projects/no-modules/consoleapp521/consoleapp521.jucer
- tests/test-projects/no-modules/consoleapp531/CMakeLists.txt
- tests/test-projects/no-modules/consoleapp531/consoleapp531.jucer
- tests/test-projects/no-modules/consoleapp543/CMakeLists.txt
- tests/test-projects/no-modules/consoleapp543/consoleapp543.jucer
> Always convert settings related to the JUCE 5 License

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
> Support "Plugin VST Num MIDI {Inputs,Outputs}" project settings

- README.rst
- cmake/IconBuilder/CMakeLists.txt
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
Resolves #442.
Resolves #444.
@stijnfrishert: FYI. Feel free to give it a try!
> Support the "Extra Custom Frameworks" and "Framework Search Paths" exporter settings

- cmake/Reprojucer.cmake
- generated/JUCE-4.3.1/CMakeLists.txt
- generated/JUCE-5.2.1/CMakeLists.txt
> Various cleanups and improvements

- docs/Reprojucer.cmake/command/jucer_appconfig_header.rst
- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- docs/Reprojucer.cmake/command/jucer_project_files.rst
- docs/Reprojucer.cmake/command/jucer_project_module.rst
- docs/Reprojucer.cmake/command/jucer_project_settings.rst
> Add several examples to the documentation of Reprojucer.cmake

- .azure-pipelines.yml
- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- README.rst
- ci/fail-if-CMake-version-3.14-or-more.cmake
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- docs/Reprojucer.cmake/index.rst
> Support the "Visual Studio 2019" exporter

- .azure-pipelines.yml
- ci/fail-if-CMake-version-3.14-or-more.cmake
- generated/JUCE-4.2.0/CMakeLists.txt
- generated/JUCE-4.3.1/CMakeLists.txt
- generated/JUCE-5.0.0/CMakeLists.txt
- generated/JUCE-5.2.1/CMakeLists.txt
- generated/JUCE-5.3.1/CMakeLists.txt
- generated/JUCE-5.4.3/CMakeLists.txt
> Build with VS2019 on CI

- README.rst
- cmake/Reprojucer.cmake
> Fix missing linker flag when enabling "Link-Time Optimisation"

- README.rst
- cmake/Reprojucer.cmake
Resolves #494.
@czyjerry, @MartyLake: please review, thanks!
> Fix missing librarian flag when enabling "Link-Time Optimisation"

- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_project_files.rst
> Support per-file compiler flags

- cmake/Reprojucer.cmake
- cmake/templates/Info.plist
> Refactor generating .plist files

- cmake/Reprojucer.cmake
- tests/test-projects/plist-generation/guiapp-MacOSX/CMakeLists.txt
A follow-up of https://github.com/McMartin/FRUT/pull/466.
> Reduce the length of jucer_project_end() again

- Jucer2Reprojucer/main.cpp
- README.rst
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
> Support the "Use IPP Library" exporter setting

- cmake/Reprojucer.cmake
> Improve some warnings

- Jucer2Reprojucer/main.cpp
> Added conversion for C++17 language standard

- README.rst
@TheSlowGrowth: please confirm that what I wrote (in the README.md and in the commit message) is all correct, thanks!
> Add Johannes Elliesen to the table of contributors

- .cirrus.yml
- .clang-format
- Jucer2Reprojucer/main.cpp
- Jucer2Reprojucer/third-party/.clang-format
- cmake/BinaryDataBuilder/extras/Projucer/Source/jucer_Headers.h
- cmake/templates/.clang-format
> Check on CI that C++ code is properly formatted

- Jucer2Reprojucer/main.cpp
A few small cleanups that I identified when reviewing #521.
> Cleanup: Use isNotEmpty() instead of !isEmpty()

- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
> Add missing documentation for the support of Unity plugins

- .cirrus.yml
- .clang-format
- Jucer2Reprojucer/main.cpp
> Indent preprocessor directives to increase readability

- .travis.yml
- Jucer2Reprojucer/main.cpp
> Fix compiling Jucer2Reprojucer with recent versions of GCC

- cmake/BinaryDataBuilder/extras/Projucer/Source/Project Saving/jucer_ResourceFile.cpp
- cmake/BinaryDataBuilder/extras/Projucer/Source/Project Saving/jucer_ResourceFile.h
- cmake/BinaryDataBuilder/extras/Projucer/Source/Utility/jucer_FileHelpers.cpp
- cmake/BinaryDataBuilder/modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniserFunctions.h
- cmake/IconBuilder/Source/Project Saving/jucer_ProjectExport_MSVC.h
- cmake/IconBuilder/Source/Project Saving/jucer_ProjectExport_XCode.h
- cmake/IconBuilder/Source/Project Saving/jucer_ProjectExporter.cpp
- cmake/IconBuilder/Source/Utility/jucer_FileHelpers.cpp
- cmake/IconBuilder/Source/Utility/jucer_FileHelpers.h
> Avoid some -Wdeprecated-declarations warnings when using JUCE 5.4.4

- cmake/BinaryDataBuilder/main.cpp
- cmake/IconBuilder/CMakeLists.txt
- cmake/IconBuilder/Source/Project Saving/jucer_ProjectExport_XCode.h
- cmake/IconBuilder/main.cpp
- cmake/Reprojucer.cmake
Quite similar to what was done on `BinaryDataBuilder` in #413.
> Upgrade IconBuilder

- Jucer2Reprojucer/main.cpp
- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/BinaryDataBuilder/main.cpp
- cmake/Reprojucer.cmake
- generated/JUCE-5.4.3/examples/DemoRunner/CMakeLists.txt
- generated/JUCE-5.4.4/examples/DemoRunner/CMakeLists.txt
> Handle bundle resources properly

- README.rst
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
> Support the "Development Team ID" exporter setting

- README.rst
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
Resolves #395
This PR is currently based on top of #546.
> Support the "In-App Purchases Capability" exporter setting

- README.rst
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
Resolves #441
This PR is currently based on top of #547.
> Support the "Add Duplicate Resources Folder to App Extension" setting

- .gitignore
- cmake/BinaryDataBuilder/extras/Projucer/Source/Project/jucer_Project.h
- cmake/IconBuilder/main.cpp
- cmake/Reprojucer.cmake
This PR is currently based on top of https://github.com/McMartin/FRUT/pull/549.
> Prepare for iOS

- ci/azure-pipelines-steps.yml
> Reduce the output of `git diff` on Azure DevOps

- .travis.yml
- Jucer2Reprojucer/main.cpp
- README.rst
> Make Reprojucer.cmake optional to convert a .jucer file

- README.rst
- cmake/Reprojucer.cmake
Resolves #562.
@dimitrisudell: could you please confirm that what I added to the README is correct?
> Fix running Rez when using the macosx10.15 SDK

- Jucer2Reprojucer/main.cpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- generated/JUCE-5.4.5/examples/DemoRunner/CMakeLists.txt
- generated/JUCE-5.4.5/extras/AudioPluginHost/CMakeLists.txt
- generated/JUCE-5.4.5/extras/Projucer/CMakeLists.txt
- generated/JUCE-5.4.5/extras/UnitTestRunner/CMakeLists.txt
> Support the "Add Recommended Compiler Warning Flags" setting

- Jucer2Reprojucer/main.cpp
- README.rst
Resolves #566.
@danra: could you please confirm that what I added to the README is correct?
> Fix converting SDK paths based on plugin formats

- Jucer2Reprojucer/main.cpp
> Fix converting the "Custom Xcode Flags" configuration setting

- Jucer2Reprojucer/main.cpp
Resolves #572.
@danra, @MartyLake: please review, thanks!
> Fix parsing preprocessor definitions

- cmake/Reprojucer.cmake
> Fix escaping parentheses in regular expressions

- cmake/Reprojucer.cmake
Resolves https://github.com/McMartin/FRUT/issues/569.
> Handle JUCE 5.3.2 targeting OS X 10.7 minimum

- cmake/Reprojucer.cmake
@MartyLake @scotchi 
As copyright holders of `Reprojucer.cmake`, please confirm your agreement to license it under the Apache License, version 2.0, by doing the following steps.
1. Edit `Reprojucer.cmake` on this branch using the GitHub UI. You can click on this link: https://github.com/McMartin/FRUT/edit/change-the-license-of-Reprojucer.cmake/cmake/Reprojucer.cmake
2. Add the copyright notice for your own name so it matches what we have on `master`:
https://github.com/McMartin/FRUT/blob/b0df7b57c003bc0316122e2cd8cfbc861ad4c14a/cmake/Reprojucer.cmake#L1-L6
(it doesn't matter in which order the lines are added, so @scotchi you don't have to wait for @MartyLake to create his commit)
3. Commit the changes using the following commit title:
```
Agree to relicense Reprojucer.cmake from GPLv3 to …
```
> Change the license of Reprojucer.cmake from GPLv3 to Apache 2.0

- Jucer2Reprojucer/main.cpp
- README.rst
> Handle properly paths that are already quoted in the .jucer file

- Jucer2Reprojucer/main.cpp
> Do not overwrite up-to-date CMakeLists.txt file

- Jucer2Reprojucer/main.cpp
Resolves https://github.com/McMartin/FRUT/issues/534.
> Do not write trailing backslashes that would break CMake lists

- Jucer2Reprojucer/main.cpp
- README.rst
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
Resolves https://github.com/McMartin/FRUT/issues/394.
> Support the "PList Preprocess" exporter setting

- README.rst
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
> Support the "Manifest file" exporter setting

- CMakeLists.txt
- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/IconBuilder/CMakeLists.txt
- cmake/PListMerger/CMakeLists.txt
- cmake/XcassetsBuilder/CMakeLists.txt
> A few style improvements

- Jucer2Reprojucer/main.cpp
- ci/apply-Jucer2Reprojucer-to-test-jucers.cmake
> Write a relative path to the .jucer file in most cases

- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_project_settings.rst
> Support the "Post-Export Shell Command" project settings

- Jucer2Reprojucer/main.cpp
> Don't write jucer_appconfig_header(...) when AppConfig.h is not found

- .appveyor.yml
- .azure-pipelines.yml
- ci/azure-pipelines-steps.yml
See https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/ for more details.
> Deal with Azure Pipelines removing the vs2015-win2012r2 hosted image

- .appveyor.yml
- .travis.yml
- README.rst
- ci/azure-pipelines-steps.yml
- cmake/tools/BinaryDataBuilder/extras/Projucer/Source/Project Saving/jucer_ResourceFile.cpp
- cmake/tools/BinaryDataBuilder/extras/Projucer/Source/Project Saving/jucer_ResourceFile.h
- cmake/tools/BinaryDataBuilder/extras/Projucer/Source/Utility/jucer_CodeHelpers.cpp
- cmake/tools/BinaryDataBuilder/extras/Projucer/Source/Utility/jucer_CodeHelpers.h
- cmake/tools/BinaryDataBuilder/extras/Projucer/Source/Utility/jucer_FileHelpers.cpp
- cmake/tools/BinaryDataBuilder/extras/Projucer/Source/Utility/jucer_FileHelpers.h
- cmake/tools/BinaryDataBuilder/extras/Projucer/Source/Utility/jucer_MiscUtilities.cpp
- cmake/tools/BinaryDataBuilder/extras/Projucer/Source/Utility/jucer_MiscUtilities.h
- cmake/tools/BinaryDataBuilder/modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniser.cpp
- cmake/tools/BinaryDataBuilder/modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniser.h
- cmake/tools/BinaryDataBuilder/modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniserFunctions.h
- cmake/tools/IconBuilder/Source/Project Saving/jucer_ProjectExport_MSVC.h
- cmake/tools/IconBuilder/Source/Project Saving/jucer_ProjectExport_XCode.h
- cmake/tools/IconBuilder/Source/Project Saving/jucer_ProjectExporter.cpp
- cmake/tools/IconBuilder/Source/Utility/jucer_FileHelpers.cpp
- cmake/tools/IconBuilder/Source/Utility/jucer_FileHelpers.h
- cmake/tools/XcassetsBuilder/Source/ProjectSaving/jucer_ProjectExport_Xcode.h
- cmake/tools/XcassetsBuilder/Source/ProjectSaving/jucer_ProjectExporter.cpp
- cmake/tools/XcassetsBuilder/Source/Utility/jucer_FileHelpers.cpp
- cmake/tools/XcassetsBuilder/Source/Utility/jucer_FileHelpers.h
- docs/index.rst
> Adapt to the JUCE repository moving to its own organization

- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
I found these while working on Jucer2CMakeLists.
> Make a few cleanups in Jucer2Reprojucer

- cmake/tools/juce_core.cmake
- cmake/tools/juce_gui_basics.cmake
> Disable GCC warnings in JUCE code

- Jucer2Reprojucer/main.cpp
> Fix calling "hasProperty" on the wrong ValueTree

- Jucer2Reprojucer/main.cpp
> More cleanups in Jucer2Reprojucer

- Jucer2Reprojucer/main.cpp
> Avoid extraneous iterations

- Jucer2Reprojucer/main.cpp
These cleanups are follow-ups of #634.
> Some post-ValueTree cleanups

- Jucer2Reprojucer/main.cpp
- README.rst
Related to my comment there: https://github.com/McMartin/FRUT/pull/638#pullrequestreview-423895627
@importjingles, @MartyLake: please review, thanks!
> Improve error messages when global paths are required

- Jucer2Reprojucer/main.cpp
> Extract function to parse arguments in Jucer2Reprojucer

- Jucer2Reprojucer/main.cpp
> Improve argument handling

- Jucer2Reprojucer/main.cpp
@importjingles: FYI, you might be interested in these changes, since we discussed them in https://github.com/McMartin/FRUT/pull/638.
> Make Jucer2Reprojucer read global paths from Projucer settings

- cmake/Reprojucer.cmake
- cmake/data/AppConfig-5.h.in
- cmake/data/JucePluginDefines.h.in
Resolves https://github.com/McMartin/FRUT/issues/623.
> Generate JucePluginDefines.h header like Projucer 6.0.0 does

- Jucer2CMake/src/main.cpp
> Improve CLI of Jucer2CMake

- Jucer2CMake/src/main.cpp
Improve certain things that were missed in https://github.com/McMartin/FRUT/pull/658.
> Improve CLI of Jucer2CMake (follow-up)

- README.rst
> Fix broken links on README

- cmake/Reprojucer.cmake
> Fix building AUv3 for iOS

- Jucer2CMake/src/juce6.hpp
- Jucer2CMake/tests/audioplug6/CMakeLists.txt
- Jucer2CMake/tests/consoleapp6/CMakeLists.txt
- Jucer2CMake/tests/guiapp6/CMakeLists.txt
This is a follow-up of https://github.com/McMartin/FRUT/pull/663.
> Polish test projects for the juce6 mode of Jucer2CMake

- cmake/Reprojucer.cmake
> Improve source file groups

- README.rst
- cmake/Reprojucer.cmake
- cmake/data/JuceHeader.h.in
> Write "companyName" field in JucerHeader.h like Projucer does

- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
> Fix typos in documentation

- cmake/Reprojucer.cmake
> Set missing PRODUCT_BUNDLE_IDENTIFIER attribute on non-bundle targets

- cmake/Reprojucer.cmake
> Use better way of defining Xcode attributes per configuration

- README.rst
- cmake/Reprojucer.cmake
> Only write comment in headers, not in preprocessor definitions 

- Jucer2CMake/src/reprojucer.hpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
> Set Xcode "ARCH" settings like Projucer does

- Jucer2CMake/src/reprojucer.hpp
- cmake/Reprojucer.cmake
- docs/Reprojucer.cmake/command/jucer_export_target.rst
> Set Xcode `*ARCH*` settings like Projucer does

- README.rst
- cmake/Reprojucer.cmake
This matches what was done in
https://github.com/juce-framework/JUCE/commit/f8e91d400, which was
released in JUCE 7.0.3.
Resolves #751
> Support building AudioUnit plugins with the AudioUnitSDK
