- .appveyor.yml
- .travis.yml
- cmake/AppConfig.h
- cmake/CMakejucer.cmake
- examples/CMakeLists.txt
- examples/audio plugin host/CMakeLists.txt
This PR adds support for `JUCE_*` config flags, which are then used in the `Plugin Host` example.
> Support JUCE_* config flags

- Jucer2CMake/main.cpp
Use the contents of the first exporter when parsing the modulepath.
> Fix parsing .projucer files with only one exporter

- Jucer2CMake/CMakeLists.txt
- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/Reprojucer.cmake
Alternative to #117.
@MartyLake: the first four commits of this PR are identical to the first four commits of #117 (i.e. only the last commit is different). Please review both PRs and tell me which one you prefer, thanks!
> Warn when jucer_export_target() isn't called with the relevant exporter

- Jucer2CMake/main.cpp
This should have been done in #120.
@MartyLake: FYI
> Clear xcodeResourcePaths like all other *Paths containers

- Jucer2Reprojucer/CMakeLists.txt
Ignore warnings generatred in juce when building with Apple LLVM version 8.1.0
> Ignore Wnullable-to-nonnull-conversion and Wcomma

- .travis.yml
Adapts to https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch.
@MartyLake: FYI
> Adapt to updated Ubuntu Trusty images on Travis CI

- cmake/Reprojucer.cmake
For consistency with target_include_directories(), target_compile_definitions(), and target_compile_options().
> Use the newer syntax of target_link_libraries()

- doc/Reprojucer.cmake/command/jucer_project_settings.rst
This should have been done in 3db7295ad0b78dcd1c690eaa65c085fd81d4bc97.
@lethal-guitar, @MartyLake: FYI (no need to review)
> Add missing closing angle bracket in doc

- Jucer2Reprojucer/CMakeLists.txt
> Fix issue with build failing on Linux with g++ v7+ due to implicit fallthrough warnings in juce-core module.

- cmake/Reprojucer.cmake
#353 actually added support for building AAX plugins with JUCE 5 only. This PR fixes this limitation by using the same logic for both JUCE 4 and JUCE 5.
> Use one target per plugin format on Windows with JUCE 4 as well

- cmake/Reprojucer.cmake
This behavior was broken in https://github.com/McMartin/FRUT/pull/374.
> Fallback to the first configuration when CMAKE_BUILD_TYPE is empty

- cmake/Reprojucer.cmake
Supersedes and closes #402.
As pointed out by @rclement, we need to pass -isysroot when executing Rez.
> Fix compiling .r resource files for AU plugins

- cmake/Reprojucer.cmake
That is in fact the variable name as it's used elsewhere in the function.
> Include JUCER_ prefix in variable reference

- cmake/Reprojucer.cmake
I'm not sure if there was a specific reason that this was attached to the target rather than providing instructions to CMake as to how to build this file, but the current code is broken for the Ninja generator (which I mostly use), and this change makes it work for all of the relevant (Ninja, make, XCode) generators.
> Specify how to generate the output file

- cmake/Reprojucer.cmake
Currently neither `OSX_DEPLOYMENT_TARGET` nor `OSX_BASE_SDK_VERSION` work for non-Xcode builds.  This fixes two issues to get things working for both of them.  This can be verified with the trivial script:
```
#!/bin/bash
otool -l $1 | grep -A4 LC_VERSION_MIN_MACOSX | head -4
```
> Fix non-Xcode macOS version targeting

- cmake/Reprojucer.cmake
This should have been done in https://github.com/McMartin/FRUT/pull/430.
> Make "Multi-Processor Compilation" properly configuration specific

- cmake/Reprojucer.cmake
This is resolving #520 partially. What is left is making Jucer2Reprojucer write valid configuration names when converting `.jucer` files, and is being worked on in #521 by @TheSlowGrowth.
> Handle configuration names that are not valid for CMake in Reprojucer.cmake

- cmake/IconBuilder/CMakeLists.txt
Pass the `-mbig-obj` option to the assembler, in case of using MinGW on windows, in order to prevent an error regarding too big object files, which is a known error for MinGW. This fixes it!
(As discussed in https://github.com/McMartin/FRUT/issues/513)
> Add the "big object files" as options for MinGW

- README.rst
- cmake/Reprojucer.cmake
Resolves https://github.com/McMartin/FRUT/issues/473.
@stijnfrishert: I was finally able to reproduce the issue when building the PushNotificationsDemo example project from JUCE 5.2.1 with Xcode 10.1 on macOS 10.13 High Sierra. Sorry for the very long delay.
> Avoid error about deprecated i386 architecture

- cmake/Reprojucer.cmake
This PR fixes a regression that was introduced in #544 and which is blocking #551.
> Fix double installation of bundle resources

- cmake/BinaryDataBuilder/CMakeLists.txt
- cmake/IconBuilder/CMakeLists.txt
- cmake/PListMerger/CMakeLists.txt
- cmake/Reprojucer.cmake
- cmake/templates/failed-to.md
This is required to support iOS (see https://github.com/McMartin/FRUT/pull/551#issuecomment-551646978).
> Support building and installing helper executables when cross-compiling

- Jucer2Reprojucer/main.cpp
Quite similar to https://github.com/McMartin/FRUT/pull/571.
> Fix invalid character escape in path to JUCE module

- cmake/Reprojucer.cmake
> Prevent CMake from interpreting "Extra Linker Flags"

- README.rst
- cmake/Reprojucer.cmake
Resolves #599.
@eyalamirmusic: please confirm that it fixes your problem and that what I wrote on the README is correct, thanks!
> Fix building projects on macOS that set a non-default BINARY_NAME

- Jucer2Reprojucer/CMakeLists.txt
- Jucer2Reprojucer/main.cpp
This is an alternative to https://github.com/McMartin/FRUT/pull/631, which should hopefully be easier to review.
> Eliminate juce::ValueTree from Jucer2Reprojucer

- README.rst
This pull request contains a small tweak to "Getting Started" which I found necessary to build.
cmake version: 3.17.3
FRUT version: (latest master) https://github.com/McMartin/FRUT/commit/affc089b9f9e603e7a2b44ed15a0eef16ea0790d
JUCE version: (latest master) https://github.com/juce-framework/JUCE/commit/02bbe31c0d2fb59ed32fb725b56ad25536c7ed75
Commands were executed on the Visual Studio Code commandline.
Folder structure:
```
<root>
├── FRUT/
│   └── build/
├── JUCE/
└── MyGreatProject/
├── Source/
└── MyGreatProject.jucer
```
In directory /FRUT/build/:
```
cmake .. -DCMAKE_INSTALL_PREFIX=../prefix -DJUCE_ROOT=../../JUCE
```
Resulted in error:
```
CMake Error: The source directory "D:/Dev/juce_projects/midi-fx/FRUT/prefix" does not exist.
```
My first instinct was to add the prefix …
> Make "Getting Started" instructions work in Windows PowerShell

- .appveyor.yml
- .azure-pipelines.yml
- .cirrus.yml
- .travis.yml
- README.rst
- docs/Reprojucer.cmake/command/jucer_appconfig_header.rst
- docs/Reprojucer.cmake/command/jucer_audio_plugin_settings.rst
- docs/Reprojucer.cmake/command/jucer_export_target.rst
- docs/Reprojucer.cmake/command/jucer_export_target_configuration.rst
- docs/Reprojucer.cmake/command/jucer_project_files.rst
- docs/Reprojucer.cmake/command/jucer_project_module.rst
- docs/Reprojucer.cmake/command/jucer_project_settings.rst
- docs/index.rst
I already changed the default branch of this repository from `master` to `main`. This PR adapts the code.
> Adapt to renaming default branch to "main"

- README.rst
- cmake/tools/juce_gui_basics.cmake
Resolves #684 
@steve-baker-cradle: please have a look at the second commit (602ece83b55f2c91677e6b1460d65dbd2068f94c) and let me know whether what I wrote is correct. Thanks!
> Fix building IconBuilder when using latest VS2019 (16.10+)

- .cirrus.yml
As @Riuzakiii found out, the formatting of `Jucer2CMake/src/reprojucer.hpp` and other `.hpp` files was not checked on CI.
> Check formatting of .hpp files on CI

- Jucer2CMake/src/reprojucer.hpp
Fixes https://github.com/McMartin/FRUT/issues/747
> Trim potential whitespaces when extracting module options

- Jucer2CMake/src/reprojucer.hpp
- README.rst
JUCE projects allow using shell script, for instance when defining post
build actions. When the shell script referred to variables using braced
notation, e. g. ${PULP}, FRUT made CMake resolve such a variable at
build system generation time instead of at build time.
For instance, given the following Post-Build Shell Script:
```
VAR="It works!"
echo "${VAR}"
```
we will end up with a postbuild.sh file with the following content:
```
VAR="It works!"
echo ""
```
As CMake will recognize `${VAR}` as a variable reference and will
immediately resolve it. The following script would works fine:
```
VAR="It works!"
echo "$VAR"
```
but the former is still a properly written shell script.
This commit treats the shell scripts as bracket arguments instead of
quoted arguments to fix this issue.
> Fix generating shell scripts with variables
